name: Release pipeline

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run release pipeline
        run: uv run poe release

      - name: Build release artifact
        run: uv run poe build

      - name: Upload release artifact
        uses: actions/upload-artifact@v7
        with:
          name: timedelta-dist
          path: dist/
